runtime: python27
api_version: 1
threadsafe: true
handlers:
    - url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
      static_files: build/\1
      upload: build/(.*)(|\.map)
    - url: /(.*)
      static_files: build/index.html
      upload: build/index.html