version: '3'
services:
  web:
    image: client
    build: ./client
    ports: 
      - "3000:3000"
    depends_on: 
      - "api"
    stdin_open: true
  api:
    image: server
    build: ./server
    depends_on: 
      - "mongo"
  mongo:
    image: "mongo"
